language: minimal
dist: xenial
before_install:
- sudo add-apt-repository -y ppa:vala-team/ppa
- sudo apt-get -q update
- sudo apt-get -y install valac meson pkg-config libgtk-3-dev libleptonica-dev libxml2-utils
install:
- git clone https://github.com/Eroica/Paletti.git
- pushd Paletti/gtk && mkdir build
- meson build && cd build
- ninja && cd ../dist
- make

addons:
  apt:
    update: true

deploy:
  provider: releases
  api_key:
    secure: GL/xcReabm0SIig2nnP4B3sFFIJdDhv3oeCKV4YdJlhP9qmkqwlJLuHpEzgTebUAR5oR282nb9sHLFgFxXB1zS0NmaA+JXrGt+dMLEZWFUXri8HF0hxhM1bX4+QaU/Bu6HYTGWiL3aJKknliBEJKLgTB400v3I2LdgTl5RjZ3PwvMIAj7cZ25GoLlprAUwUvOLVBwEz5UleGYUi9RAbgmK4m2VkrBUdZIL7uSs6BLdmKMaSDMhysfFcvhZ1Pk3g3YQAPITTssqLZzNs92sNNyqHs8UEN5TZAw5c64bYL8H3E6wLpvZ5ar6aZogPBLHVkLiYu5DQAUcCJZjlqr5FaIk2KjWFfQHhN15oczkCdo5JcKPDwvH4DoD06ZNTe7v1pltqBxrkCHDcAAzD41nziBFYnW5h50wvprHitXpqxBUkBMxChLddWH6+BxaBfeWWf5qMcGyCInNdTKcA28qRQcf3lCe4pqVuDsiaQFV7dZOnHXyljrgBGbxWGg8z2cKxRD6ygsXQa7z8v8HHmEZDJ+pLhvKKhU3drYhDVupc6F7Cj1T26thoE5+hQbGHYhvPm9tn5umEM08CM1aTwuZLFjPDG11lhJjKXq9ICVFTuiP5NBa5WgRjrYkkLuWMzQFRzM+KiwihBuqU8Zh0xT4hz8GWazfXOzb5tt1np2tuq/Xo=
  file_glob: true
  file: Paletti-*.AppImage
  on:
    repo: Eroica/Paletti
    tags: true
  skip_cleanup: true
