# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paletti
# description: > # this means to ignore newlines until "baseurl:"
description: A color quantization tool built for artists and designers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paletti.app" # the base hostname & protocol for your site
author: Eroica

# excerpt_separator: ""
permalink: pretty

# Build settings
theme: jekyll-hypertext-theme
markdown: kramdown
sass:
  style: compressed

exclude:
  - package-lock.json
  - package.json
